#!/bin/bash
#SBATCH --job-name=gfslt-semantic
#SBATCH --partition=a100
#SBATCH --gres=gpu:1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=10
#SBATCH --mem=100G
#SBATCH --time=0-12:00:00
#SBATCH --output=logs/debug_output-%j.log
#SBATCH --error=logs/debug_error-%j.log

# Set environment variables for torchrun
export HOST_NUM=${SLURM_NNODES}
export INDEX=${SLURM_PROCID}
export HOST_GPU_NUM=${SLURM_GPUS_ON_NODE}
export CHIEF_IP=$(scontrol show hostname $SLURM_NODELIST | head -n 1)

# Debugging: Print values to verify they're set correctly
echo "HOST_NUM: $HOST_NUM"
echo "INDEX: $INDEX"
echo "HOST_GPU_NUM: $HOST_GPU_NUM"
echo "CHIEF_IP: $CHIEF_IP"

# Additional environment variables for torchrun
export TORCH_DISTRIBUTED_DEBUG=DETAIL
export WANDB_API_KEY=b3a33bb694f0df2dfbd61a052b8e6d5aef47dba6

# Run the training command
apptainer exec --nv --bind /vol/vssp --bind /mnt/fast slt_apptainer.sif bash -c "
    source /opt/conda/etc/profile.d/conda.sh	
    conda activate slt
    echo 'Running torchrun with the following args:'
    
    TORCH_DISTRIBUTED_DEBUG=DETAIL HF_DATASETS_OFFLINE=0 TRANSFORMERS_OFFLINE=0 torchrun --nnodes=${HOST_NUM} --node_rank=${INDEX} --nproc_per_node=${HOST_GPU_NUM} --master_addr=${CHIEF_IP} --master_port=29501 \
    -m train_vlp_v2 \
    --local_rank ${INDEX}
    --batch-size 10 \
    --epochs 80 \
    --opt sgd \
    --lr 0.01 \
    --output_dir out/vlp_v2_cluster \
    --noise-rate 0.15 \
    --noise-type omit_last \
    --random-shuffle True \
    --project "VLP-Semantic-Loss"
"
    
